# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='username',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='prodact',
            name='owner',
        ),
    ]
