# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labApp', '0002_auto_20171101_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='prodact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labApp.Prodact', verbose_name='продукт'),
        ),
    ]
