# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-14 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labApp', '0008_auto_20171212_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='type',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Monoblock', 'Monoblock'), ('Personal Computer', 'Personal computer')], default='Personal Computer', max_length=30),
        ),
    ]
